services:
  - type: web
    name: writeful-fe
    env: static
    buildCommand: cd blog-fe && npm install && npm run build
    staticPublishPath: blog-fe/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
